### ISSUE TITLE
How can i use the version "OS X" it doesn*t work for me

### ISSUE THREAD

**Issue by GitSimonHub** [TeaSpeak/TS3Hook#38] opened 2018-05-19 21:45 UTC
Hey, 
this is the HookConfig, but if i try to join a Server it says "Modified Client"
Thanks:

[Config]
outprefix=[OUT]
outsuffix=
inprefix=[IN ]
insuffix=
ignorecmds=
blockcmds=connectioninfoautoupdate,setconnectioninfo
clientversion=3.1.9 [Build: 1525442084]|OS X|WVaMmYPig4eG2JUM8cMMW2MA7+IoRoPUSr74CPe7oS8TLHGjYxPr1FP88op6YsFFQrPJysWmIsnGR7BiFXjHCQ==
bypass_modalquit=1
teaspeak_anti_error=1

**Comment by Bluscream** [comment] 2018-05-19 21:57
Duplicate of #36

**Closed by Bluscream** 2018-05-19 21:57 UTC
